name: Unlock-NetEaseMusic

on:
  schedule:
    - cron: "37 */8 * * *"  # 每8小时运行一次
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Chrome & Chromedriver
        run: |
          choco install googlechrome -y
          choco install chromedriver -y --force

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install selenium retrying

      - name: Run unlock script
        run: python auto_login.py

      - name: Upload screenshot
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: after-login-screenshot
          path: after_login.png
